name: checking branch through context variables

on:
  workflow_dispatch:

jobs:
  branch-check:
    name: branch checking
    runs-on: ubuntu-latest

    steps:
      - name: print refs
        run: |
          echo "Full ref info: ${{ github.ref }}"
          echo "Only branch or tag: ${{ github.ref_name }}"
