name: checking branch through context variables
on: 
  workflow_dispatch:

jobs:
  name: branch checking
    runs-on: ubuntu-latest
    steps:
      - name: print refs
        run: |
          echo "full info using ${{  github.ref      }}"
          echo "pnly branch or tag using ${{ github.ref_name}}"    
  
